import type { Metadata } from "next";
import "./style/globals.css";
import React from "react";
import Theme from "@/app/theme/Theme";
import LayoutWrapper from "@/app/components/LayoutWrapper";
import StyledJsxRegistry from "@/app/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export interface ILanguage {
  lang: any;
}

export interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <Theme>
        <body>
          <StyledJsxRegistry>
            <LayoutWrapper locale={params.locale}>{children}</LayoutWrapper>
          </StyledJsxRegistry>
        </body>
      </Theme>
    </html>
  );
}
